// This allows the API project to access extension methods
// defined inside the Infrastructure project (like AddInfrastructure)

using BarberSaaS.Infrastructure;

var builder = WebApplication.CreateBuilder(args);

// Enables controller-based APIs (required for using Controllers folder)
builder.Services.AddControllers();


// Registers Swagger / OpenAPI services
// This prepares Swagger internally (it does NOT expose endpoints yet)

builder.Services.AddInfrastructure(builder.Configuration);


builder.Services.AddOpenApi();


// Registers all Infrastructure services (DbContext, repositories, etc.)
// This connects the API layer with the Infrastructure layer
// Without this, controllers that depend on Infrastructure will crash
builder.Services.AddInfrastructure(builder.Configuration);

//(This tells the app to look for mapping configurations in your project).
builder.Services.AddAutoMapper(typeof(Program));

var app = builder.Build();

// Configure the HTTP request pipeline.
// Everything here controls HOW incoming HTTP requests are handled.

if (app.Environment.IsDevelopment())
{
    // Exposes the OpenAPI JSON document
    // This is the machine-readable description of your API
    // Swagger UI reads THIS file to know what endpoints exist
    app.MapOpenApi();

    // Enables the Swagger UI (the web page you open in the browser)
    // This is NOT the API itself — it is just documentation
    app.UseSwaggerUI(options =>
    {
        // Tells Swagger UI where the OpenAPI JSON file is located
        // "/openapi/v1.json" is generated by app.MapOpenApi()
        options.SwaggerEndpoint("/openapi/v1.json", "BarberSaaS API v1");

        // Defines the URL where Swagger UI is available
        // With this setting, you open Swagger at:
        // https://localhost:<port>/swagger
        options.RoutePrefix = "swagger";
    });
}


// Forces HTTPS usage
app.UseHttpsRedirection();

// Maps controller routes (e.g. /api/barbershops)
// Without this, controllers will never be reachable
app.MapControllers();


app.Run();


